version: "3.9"

services:

  app_file:
    build: .
    container_name: app_file
    command: ['./start.sh']
    depends_on:
      - db
    ports:
      - "8090:8090"

  db:
    image: postgres
    container_name: "db_file"
    volumes:
      - pg_d:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

volumes:
  pg_d:
